port: 8080
logLevel: info # Choose one of the following: debug, info, warn, error, default to info
logMode: text # Choose one of the following: json, text, default to text
systemPrompt: You are a helpful assistant.
titleGeneratorPrompt: Generate a title for this chat with only one sentence with maximum 5 words.
# Choose one of the following LLM providers: ollama, anthropic
llm:
  provider: ollama
  model: claude-3-5-sonnet-20241022
  # ollama
  host: http://localhost:11434 # Default to environment variable OLLAMA_HOST
  # anthropic
  apiKey: YOUR_API_KEY # Default to environment variable ANTHROPIC_API_KEY
  maxTokens: 1000
  # openai
  apiKey: YOUR_API_KEY # Default to environment variable OPENAI_API_KEY
  # openrouter
  apiKey: YOUR_API_KEY # Default to environment variable OPENROUTER_API_KEY
genTitleLLM: # Default to the same LLM as the main LLM
  provider: anthropic
  model: claude-3-5-sonnet-20241022
  apiKey: YOUR_API_KEY # Default to environment variable ANTHROPIC_API_KEY
  maxTokens: 1000
mcpSSEServers:
  filesystem:
    url: https://yoursseserver.com
mcpStdIOServers:
  filesystem:
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-filesystem"
      - "/home/gs/repository/go-mcp"
